<a href="https://colab.research.google.com/github/anand12yadav/Handling-Imbalanced-Dataset-Machine-Learning/blob/master/Handling_Imbalanced_Dataset_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Handling imbalanced dataset in Machine learning

In [ ]:
!pip install imbalanced-learn 

In [ ]:
import pandas as pd
df=pd.read_csv("creditcard.csv")

df.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [ ]:
df.shape

(284807, 31)

In [ ]:
df.isnull().sum()

In [ ]:
# dependent feature is Class here in the dataset
# lets check how many 0's and 1's present 
# 0 represents not fraud , 1 reperesents fraud

df["Class"].value_counts()

# Now we can see there is huge difference between the two so its imbalanced data

0    284315
1       492
Name: Class, dtype: int64

In [ ]:
# dividing the dataset into independent and dependent feature (X=independent features , Y= dependent feature)

X=df.drop("Class",axis=1)
Y=df["Class"]


*Cross Validation like KFOLD and Hyperparameter Tuning*

In [ ]:
# lets just apply logistic regression (you can choose any algo) algorithm to the dataset and see what happens 
# Just to check performance

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

from sklearn.model_selection import KFold # using this library for cross validation
import numpy as np
from sklearn.model_selection import GridSearchCV


In [ ]:
log_class=LogisticRegression()
# performing hyper parameter tuning 
# C ,penalty is the parameter prresent in LogisticRegression()
grid={"C": 10.0**np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,shuffle=False,random_state=None)



In [ ]:
# Performing Train Test split 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,train_size=0.7)

In [ ]:
# n_jobs uses all the cores of the computer 
# f1_macro its like accuracy
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_macro', verbose=0)

In [ ]:
y_predict=clf.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(accuracy_score(y_test,y_predict))  # better accuracy does not always means that the model is good, here we get 99% accuracy because the numbers of 1's were very very less than 0's
print(classification_report(y_test,y_predict))

[[85237    48]
 [   49   109]]
0.9988647402361809
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85285
           1       0.69      0.69      0.69       158

    accuracy                           1.00     85443
   macro avg       0.85      0.84      0.85     85443
weighted avg       1.00      1.00      1.00     85443



In [ ]:
# Lets perform same with some other alogithm like RandomForest 
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
# Here i have not performed cross validation,Hyperparameter tuning , we can perform if want similar to example above
# If we apply cross validation and Hyperparameter tuning we will get more better results
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_predict=classifier.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(accuracy_score(y_test,y_predict))   
print(classification_report(y_test,y_predict))

[[85276     9]
 [   39   119]]
0.9994382219725431
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85285
           1       0.93      0.75      0.83       158

    accuracy                           1.00     85443
   macro avg       0.96      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



**Technique 1 :Under sampling** 

 what do we do in undersampling ?

 Suppose we have 0 - 10000 values for 0 and 1-100 values for 1 as here the data is imbalanced .
 
 we will do undersampling ---undersampling will reduce the points of maximum labels , means here 0's points are maximum it will reduce 0's points from 1000 to 500 maybe or anything.

 This method has various disadvantages so it should not be used for large datasets , it ahould be used for small datasets.

In [ ]:
y_train.value_counts()
# we will try to reduce the 0's vaue by 80% as here we can see its values is way more than 1's

0    199030
1       334
Name: Class, dtype: int64

In [ ]:
# this library counts the number of 0's and 1's
from collections import Counter
# need this library to perform under sampling 
from imblearn.under_sampling import NearMiss
ns = NearMiss(0.8)
# we use fit_sample for this rather than fit()
X_train_ns,y_train_ns=ns.fit_sample(X_train,y_train)
print("The number of Class befor fit {}".format(Counter(y_train)))
print("The number of Class after fit {}".format(Counter(y_train_ns)))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


The number of Class befor fit Counter({0: 199030, 1: 334})
The number of Class after fit Counter({0: 417, 1: 334})


In [ ]:
# Lets perform same with some other alogithm like RandomForest 
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
# Here i have not performed cross validation,Hyperparameter tuning , we can perform if want similar to example above
# If we apply cross validation and Hyperparameter tuning we will get more better results
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_predict=classifier.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(accuracy_score(y_test,y_predict))   
print(classification_report(y_test,y_predict))

[[61841 23444]
 [   12   146]]
0.725477803916061
              precision    recall  f1-score   support

           0       1.00      0.73      0.84     85285
           1       0.01      0.92      0.01       158

    accuracy                           0.73     85443
   macro avg       0.50      0.82      0.43     85443
weighted avg       1.00      0.73      0.84     85443



# Technique 2 :Over Sampling.

 In over sampling those which has less values we increase their value. 

 Here 1's values where less as compared to 0's , so we will increas the values of 1's.



In [ ]:
# library to perform over sampling 
from imblearn.over_sampling import RandomOverSampler


In [ ]:
# this library counts the number of 0's and 1's
from collections import Counter
os = RandomOverSampler(0.5)
# we use fit_sample for this rather than fit()
X_train_ns,y_train_ns=os.fit_sample(X_train,y_train)
print("The number of Class befor fit {}".format(Counter(y_train)))
print("The number of Class after fit {}".format(Counter(y_train_ns)))

The number of Class befor fit Counter({0: 199030, 1: 334})
The number of Class after fit Counter({0: 199030, 1: 99515})


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
# Lets perform same with some other alogithm like RandomForest 
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
# Here i have not performed cross validation,Hyperparameter tuning , we can perform if want similar to example above
# If we apply cross validation and Hyperparameter tuning we will get more better results
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_predict=classifier.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(accuracy_score(y_test,y_predict))   
print(classification_report(y_test,y_predict))

[[85276     9]
 [   37   121]]
0.9994616293903538
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85285
           1       0.93      0.77      0.84       158

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



# Technique 3 : SMOTETomek

This technique uses the combination of udersampling and oversampling.

It creates new points for the lowest value among the two

In [ ]:
# Library used for this technique
from imblearn.combine import  SMOTETomek


In [ ]:
# this library counts the number of 0's and 1's
from collections import Counter
os = SMOTETomek(0.75)
# we use fit_sample for this rather than fit()
X_train_ns,y_train_ns=os.fit_sample(X_train,y_train)
print("The number of Class befor fit {}".format(Counter(y_train)))
print("The number of Class after fit {}".format(Counter(y_train_ns)))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


The number of Class befor fit Counter({0: 199030, 1: 334})
The number of Class after fit Counter({0: 198463, 1: 148705})


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
# Lets perform same with some other alogithm like RandomForest 
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
# Here i have not performed cross validation,Hyperparameter tuning , we can perform if want similar to example above
# If we apply cross validation and Hyperparameter tuning we will get more better results
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_predict=classifier.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(accuracy_score(y_test,y_predict))   
print(classification_report(y_test,y_predict))

[[85262    23]
 [   32   126]]
0.9993562960102056
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85285
           1       0.85      0.80      0.82       158

    accuracy                           1.00     85443
   macro avg       0.92      0.90      0.91     85443
weighted avg       1.00      1.00      1.00     85443



# Technique 4 : Ensemble Techniques

In [ ]:
# library to use this technique 
from imblearn.ensemble import EasyEnsembleClassifier



In [ ]:
easy=EasyEnsembleClassifier()
easy.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarni

EasyEnsembleClassifier(base_estimator=None, n_estimators=10, n_jobs=1,
                       random_state=None, replacement=False,
                       sampling_strategy='auto', verbose=0, warm_start=False)

In [ ]:
y_predict=easy.predict(X_test)
print(confusion_matrix(y_test,y_predict))
print(accuracy_score(y_test,y_predict))   
print(classification_report(y_test,y_predict))

[[82317  2968]
 [   16   142]]
0.9650761326264293
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     85285
           1       0.05      0.90      0.09       158

    accuracy                           0.97     85443
   macro avg       0.52      0.93      0.53     85443
weighted avg       1.00      0.97      0.98     85443

